### ISSUE TITLE
Attribute error in macOS recovery

### ISSUE THREAD

**Issue by imerzan** [imerzan/UserBackup#4]
User indicates this is not working properly in macOS recovery mode. Log file is spammed with the following:
```
09/15/2021 15:17:01: ERROR Worker #0: System.IO.IOException: Attribute not found
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Interop.CheckIo(Int64 result, String path, Boolean isDirectory, Func`2 errorRewriter)
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at UserBackup.BackupWorker.Worker(Int32 t) in BackupWorker.cs:line 35
```

Was able to reproduce bug in macOS Big Sur (recovery)

**Comment by imerzan** [comment]
Switched to a `FileStream` implementation that corrected this issue. No longer using `File.Copy` API.

**Comment by imerzan** [comment]
Reverted in 26eeccb , this is no longer a problem in .NET6
